### ISSUE TITLE
how to make these color txt files ?

### ISSUE THREAD

**Issue by baifengbai** [mzucker/fit_colormaps#1]

**Comment by mzucker** [comment]
I copy/pasted data from https://github.com/BIDS/colormap/blob/master/colormaps.py

HSLuv and HSPuv were obtained thru this code: https://github.com/hsluv/hsluv-python -- I may eventually upload a script to generate those palettes.

-Matt

**Comment by mzucker** [comment]
Added a new file `generate_hsluv_data.py` in commit b21715d.
